- name: SSH Remote Commands
  uses: appleboy/ssh-action@v0.1.4
  on: [ push ]
  jobs:

    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: 22
            script: |
              whoami
              git clone https://github.com/watislaf/ElevatorSystem.git
              cd ./ElevatorSystem            
              bash ./setupDocker.sh